name: Python C Extension Test with Coverage

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install scikit-build-core cmake

    - name: Install lcov
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov

    - name: Configure and build the C extension
      run: |
        # Build the project
        pip install .  # This builds both the Python extension and the C executable

    - name: Install test dependencies
      run: |
        python -m pip install numpy pytest

    - name: Run pytest
      run: |
        pytest test/test_rstatspy.py

    - name: Build and run the C executable to generate coverage data
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_C_FLAGS="--coverage" \
              -DCMAKE_EXE_LINKER_FLAGS="--coverage"
        cmake --build build
        cd build
        ./test_rstatspy ../test/test_rstatspy.py
        lcov --rc lcov_branch_coverage=1 --capture --directory . --output-file coverage.info 
        lcov --remove coverage.info '/usr/*' --output-file coverage.info  # Remove coverage for system files.
        lcov --rc lcov_branch_coverage=1 --list coverage.info

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: build/coverage.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        codecov_yml_path: .github/codecov.yml