name: Build and upload to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_wheels:
    env:
      CIBW_PROJECT_REQUIRES_PYTHON: ">=3.7"
      CIBW_ENVIRONMENT: 'LD_LIBRARY_PATH=$(pwd)/build/src/rstats/src/rstats${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}'
      CIBW_SKIP: "pp39*-manylinux_i686 pp3[1-9][0-9]-manylinux_i686"
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [macos-14] #, macos-13, macos-14, ubuntu-latest, windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: /dist
          

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
  
  pypi-publish:
    name: Upload release to PyPI
    needs: 
      - build_wheels
      - build_sdist
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/rstatspy 
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    # retrieve your distributions here

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1.10